=== Likhith-2914/Streaming-Lattice-Of-Cuboids/Lattice/src/main/java/org/example/lattice/streamSchema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="tick">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="tick_type" type="xs:string" />
                <xs:element name="tick_count" type="xs:string" />
                <xs:element name="tick_units" type="xs:string" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="velocity">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="velocity_type" type="xs:string" />
                <xs:element name="velocity_count" type="xs:string" />
                <xs:element name="velocity_units" type="xs:string" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>


    <xs:element name="streamdefination">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="databaseName" type="xs:string"/>
                <xs:element minOccurs="1" ref="tick"/>
                <xs:element minOccurs="1" ref="velocity"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Likhith-2914/Streaming-Lattice-Of-Cuboids/Lattice/src/main/java/org/example/lattice/streamSchema.xml
<?xml version="1.0"?>
<streamdefination xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:noNamespaceSchemaLocation="streamSchema.xsd">
    <databaseName>market_db</databaseName>
    <tick>
        <tick_type>physical</tick_type>
        <tick_count>5</tick_count>
        <tick_units>seconds</tick_units>
    </tick  >
    <velocity>
        <velocity_type>physical</velocity_type>
        <velocity_count>2</velocity_count>
        <velocity_units>seconds</velocity_units>
    </velocity>
</streamdefination>
